# pubspec.yaml

name: ossmm
description: A Flutter project for OSSMM.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter

  # Core BLE functionality
  flutter_blue_plus: ^1.35.0

  # BLUE Bond State
  shared_preferences: ^2.5.3  # For storing bonded device information

  # State Management
  provider: ^6.1.2

  # File handling
  path_provider: ^2.1.3

  # Permissions
  permission_handler: ^12.0.0+1

  # Date Formatting
  intl: ^0.20.2

  cupertino_icons: ^1.0.8

  # Data Storage and Encryption
  archive: ^4.0.7
  flutter_secure_storage: ^8.0.0
  encrypt: ^5.0.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  # assets:
  # fonts:

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/app_icon.jpg"
  min_sdk_android: 21